
language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq protobuf-compiler libprotobuf-java libprotobuf-dev python-protobuf python-mock python-gflags python-requests python-dev
 - sudo pip install ecdsa 'Twisted>=12.1'
 - sudo ln -s protobuf-java.jar /usr/share/java/protobuf.jar
 - mkdir -p $GOPATH/src/github.com/google
 - ln -s $PWD $GOPATH/src/github.com/google
 - go get -v -d ./...
 - java -version
 - javac -version

script:
 - ant test
# TODO(pphaneuf): We would like simply ./go/... here, but it doesn't work yet.
 - go test -v ./go/asn1/... ./go/client/... ./go/scanner/... ./go/x509/...
 - make -C python test
